### ISSUE TITLE
Fails to work with nrepl 0.5.3 and consequently leiningen 2.8.3

### ISSUE THREAD

**Issue by RickMoynihan** [vvvvalvalval/scope-capture-nrepl#3]
Yields the stacktrace:

```
[WARNING] No nREPL middleware descriptor in metadata of #'sc.nrepl.middleware/wrap-letsc, see nrepl.middleware/set-descriptor!
nREPL server started on port 63085 on host 127.0.0.1 - nrepl://127.0.0.1:63085
Exception in thread "nREPL-worker-0" java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: cider.nrepl.middleware.track_state$make_transport$reify__11881
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at nrepl.transport$eval2274$fn__2275$G__2265__2282.invoke(transport.clj:16)
	at nrepl.middleware.interruptible_eval$evaluate$fn__2829$fn__2843.invoke(interruptible_eval.clj:125)
	at clojure.main$repl$fn__9077.invoke(main.clj:437)
	at clojure.main$repl.invokeStatic(main.clj:435)
	at clojure.main$repl.doInvoke(main.clj:345)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate$fn__2829.invoke(interruptible_eval.clj:83)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:81)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:50)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__2872$fn__2875.invoke(interruptible_eval.clj:221)
	at nrepl.middleware.interruptible_eval$run_next$fn__2867.invoke(interruptible_eval.clj:189)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Incidentally I have already patched a fix this, and will issue a PR for it shortly.

**Comment by vvvvalvalval** [comment]
Thx, that was to be expected indeed. Will await your fix.
